#test robot
name: Automatisasi Preprocessing Superstore

on: [push]

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # Kita tambahkan openpyxl agar Python bisa membaca file .xlsx kamu
    - name: Install Dependencies
      run: |
        pip install pandas numpy scikit-learn openpyxl

    # Memanggil skrip otomatisasi dengan nama file asli kamu
    - name: Run Preprocessing Script
      run: python preprocessing/automate_husein.py